### ISSUE TITLE
Resolução na versão 8.4.1.6

### ISSUE THREAD

**Issue by RaCastroBR** [wilsade/Informativus#11]
Ao atualizar para a versão 8.4.1.6 o app não está sendo exibido corretamente quando se utiliza resolução diferente de 100% no Windows.

No print em anexo, por exemplo, a resolução do Windows está configurada para 125%

![image](https://user-images.githubusercontent.com/83226821/116107120-2071ee80-a689-11eb-958f-3321c54c157a.png)

**Comment by wilsade** [comment]
Ajuste realizado.
Disponível na versão 8.4.1.7.
