### ISSUE TITLE
Dock Lista de tabelas fechando

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#12]
Com o dock sem estar fixado na sua exibição, ao clicar no link "Procurar Tabelas / Campos específicos" e apertar ENTER, o dock é fechado e não é executado nenhum filtro. Ao clicar em PROCURAR, o filtro é realizado, mas o dock também é fechado antes de mostrar o resultado.

O comportamento só fica normal caso o dock esteja fixado.

**Comment by wilsade** [comment]
Situação simulada.
Inclusive, o dock também é fechado ao clicar, ou no botão PROCURAR, ou no label "Tabelas / Views".
Será ajustado e estará disponível na próxima versão.

**Comment by wilsade** [comment]
Ajustado.
Disponível na versão 8.4.1.8, ou superior
