### ISSUE TITLE
Conexão com o banco Oracle

### ISSUE THREAD

**Issue by boyshot** [wilsade/Informativus#13]
Ao abrir a ferramenta e digitar o servidor e Base Oracle ocorre o erro abaixo:

Observação: Este erro ocorre para cada caractere que digito. Ainda sim consigo conectar no banco no final.

![Erro Banco](https://user-images.githubusercontent.com/19939381/118481732-2e47ec00-b6ea-11eb-951d-f7ade97c2cd6.png)

Tela: Conexão com o banco de dados: Tipo Oracle

System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Informativus.Forms.UserControls.OracleConexaoControl.<GetItemNoTextoDoCombo>b__28_0(BaseDadosOracleItem x)
   em System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   em Informativus.Forms.UserControls.OracleConexaoControl.comboServidores_TextChanged(Object sender, EventArgs e)
   em System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   em System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   em System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   em System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   em System.Windows.Forms.ComboBox.WndProc(Message& m)
   em ComponentFactory.Krypton.Toolkit.KryptonComboBox.InternalComboBox.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by wilsade** [comment]
Bom dia.
Qual a versão que você está usando?

**Comment by boyshot** [comment]
Oracle: 19c
Informativus: 8.4.1.7

**Comment by wilsade** [comment]
Não consegui simular esta situação.

No diretório C:\Users\<seu usuario>\AppData\Local\Informativus, existem dois arquivos:
* Servidores.xml;
* UltimasConexoes.xml

Consegue me mandar por email? Talvez seja alguma peculiaridade dos arquivos de configuração.
Obrigado.

**Comment by wilsade** [comment]
O problema ocorria devido a um erro no parser do Informativus que lê o arquivo TnsNames.ora.
Ao que tudo indica, um dos arquivos no servidor testado não era válido.

Foi feito a correção no Informativus.
Correção disponível na versão 8.4.1.11 (ou superior).
