### ISSUE TITLE
Ao perder a conexão com base Oracle, a conexão não é reestabelecida automaticamente

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#14]
Ao realizar algumas consultas em banco de dados Oracle e deixar o Informativus minimizado por um longo período, a conexão com o Oracle é perdida.

Isso é percebido após a execução de uma nova consulta, mostrando a mensagem abaixo:
![image](https://user-images.githubusercontent.com/22624613/132902121-15fb5fc2-5acb-4590-a865-0eace7dc15a5.png)

Até este momento, um comportamento normal.

Porém, ao tentar realizar novamente a consulta após a exibição desta mensagem, a conexão com a base não é reestabelecida automaticamente conforme é feita com banco SQL Server. Isso força a necessidade de fechar a conexão atual com a base Oracle na lista de Conexões, e abrir uma nova conexão para enfim, reestabelecer a conexão.

**Comment by wilsade** [comment]
Duplicated: https://github.com/wilsade/Informativus/issues/4
