### ISSUE TITLE
Erro no documento XML (0, 0) ao  abrir o informativus

### ISSUE THREAD

**Issue by rafaelbdantas** [wilsade/Informativus#15]
![image](https://user-images.githubusercontent.com/3748325/133305800-ec8ef072-f178-427b-81a0-2514492256b4.png)

**Comment by wilsade** [comment]
Boa tarde.

Em que momento ocorre o erro?
Qual foi o stack da exceção?
O Informativus foi instalado em qual pasta?

Obrigado.

**Comment by wilsade** [comment]
A causa mais provável é que o arquivo antigo de configuração do Informativus esteja corrompido.
Tente excluir o arquivo em:
* C:\Users\<SeuUsuario>\AppData\Local\Informativus\Informativus.cfg

Se o erro persistir, é possível abrir cada XML e ver qual deles está corrompido.
Caso não tenha identificado, remova demais XMLs.

Grato.
