### ISSUE TITLE
Modernização da caixa de pesquisa do Informativus

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#16]
Seria importante a pesquisa do Informativus sofrer uma modernização.
É custoso realizar pesquisas em strings de consultas extensas, devido a baixa usabilidade do formulário de pesquisa. Há casos onde fica mais prático copiar o conteúdo da consulta para um outro editor de texto, fazer as pesquisas/replaces necessárias e depois voltar a colar o resultado final no Informativus para realizar a consulta.

Sugiro a melhoria para uma pesquisa conforme existente no Visual Studio Code/Sublime Text/SQL Server Managment Studio onde o formulário de pesquisa seja menor e o texto da consulta continue sendo acessível para seleção/edição mesmo com o formulário de pesquisa aberto. Isso torna possível você selecionar ou copiar "novas strings", para colar no campo de pesquisa e continuar a busca por novos termos.

Outros recursos importantes:

1) Marcar visualmente no editor todas as ocorrências encontradas com o termo pesquisado. Atualmente ao parar o cursor em cima do nome de uma tabela ou campo, o Informativus já marca no editor a palavra em outros pontos da consulta, o que não acontece ao mostrar o resultado da pesquisa... Expandir este comportamento ao mostrar o resultado.

2) Ao selecionar um trecho de string no editor e apertar Control + F (mesmo com o formulário de pesquisa já aberto), o termo selecionado se torna o novo conteúdo do campo de pesquisa, e o resultado da pesquisa é exibido em seguida.

**Comment by wilsade** [comment]
Está sendo implementado.
Estará disponível na versão 8.4.2.1 (ou superior)

**Comment by wilsade** [comment]
Implementado
