### ISSUE TITLE
O Plugin de geração de DataProps deveria funcionar na consulta SQL

### ISSUE THREAD

**Issue by mkazimoto** [wilsade/Informativus#18]
Normalmente fazemos um consulta SQL com JOIN com outras tabelas, por isso o plugin de geração de DataProps deveria funcionar na consulta SQL.

**Comment by wilsade** [comment]
Quaisquer alterações no plugIn podem ser feitas.
O fonte de geração de código RM encontra-se no git; https://github.com/wilsade/Informativus/blob/master/Informativus.Plugins.sln

Esteja à vontade para implementar o novo _EntryPoint_ e submeter um Pull Request.
Grato pela atenção.
