### ISSUE TITLE
Comandos PLUGGABLE DATABASE(Oracle) apresenta erro de sintaxe

### ISSUE THREAD

**Issue by fabitu** [wilsade/Informativus#19]
Bom dia Sade,

Conforme conversado os comandos abaixo não são executados em oracle pois fala que apresenta erro de sintaxe.

ALTER PLUGGABLE DATABASE TAE CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE TAE INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE TAE FROM EXEMPLO1212302;
ALTER PLUGGABLE DATABASE TAE OPEN;

Mensagem de error
[ALTER PLUGGABLE DATABASE TAE CLOSE IMMEDIATE; ...]
Ocorrera(m) erro(s) na execução do comando Sql
ALTER(1,1) expected token:Error when tokenize

**Comment by wilsade** [comment]
Este parser é feito através de DLL de terceiros.
Não tem como atuar.
Uma solução de contorno é desconsiderar o Parser na consulta.
Veja um exemplo:
`-- $PARSER$`
`ALTER PLUGGABLE DATABASE TAE CLOSE IMMEDIATE;`
