### ISSUE TITLE
Erro ao fazer um replace por uma string entre chaves

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#20]
Ao fazer um Replace ou Find da string "{0}" no conteúdo da consulta SQL, ocorre o erro abaixo:

![image](https://user-images.githubusercontent.com/22624613/227317737-e6d16516-3b1d-4ecf-9660-33d8c8c924e7.png)

**Comment by wilsade** [comment]
Resolvido.
Estará disponível na próxima atualização (versão 8.4.4.2, ou superior)
