### ISSUE TITLE
Campo de endereço do servidor de base Oracle na janela de nova Conexão

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#21]
O campo do endereço do servidor/base quando selecionado bases Oracle poderia ser consideravelmente maior para ser possível diferenciar o final do texto do seu conteúdo, já que em bases Oracle o conteúdo deste campo fica extenso contendo o NOMESERVIDOR/NOMEBASEDADOS.

Em alguns casos se diferencia a base desejada através dos ultimos caracteres, e um campo maior pode facilitar a visualização de todo o texto, conforme exibido abaixo quando a lista dos nomes de bases que já foram acessadas anteriormente são exibidas.

![image](https://user-images.githubusercontent.com/22624613/230820276-3a70614e-27ea-4558-810e-f45fef96fb0b.png)

**Comment by wilsade** [comment]
O comprimento do DropDown do ComboBox foi aumentado.
![image](https://user-images.githubusercontent.com/14340865/231014145-fac314e2-f114-40ca-a506-0ac9ba0c6366.png)

Estará disponível na próxima atualização (versão 8.4.4.3, ou superior)
