### ISSUE TITLE
ORA-00904: "NOLOCK": invalid identifier

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#23]
Ao estar conectado em um banco de dados ORACLE, clicar com o botão direito em cima de uma tabela na lista de "Tabelas recentes", no menu "Geração > INSERT / UPDATE / DELETE", abrir a tela que configura as colunas que farão parte do comando a ser gerado e clicar no botão "Gerar" conforme o print, ocorre o seguinte erro: "Não foi possível gerar o script.

Motivo: ORA-00904: "NOLOCK": invalid identifier
Help: https://docs.oracle.com/error-help/db/ora-00904/"

![image](https://github.com/user-attachments/assets/5eb21351-fa74-45bc-a95f-fbe1909e50cb)

**Comment by wilsade** [comment]
Situação simulada.
Como solução de contorno, basta remover o comando "(NOLOCK)" que o script será gerado.

**Comment by wilsade** [comment]
Corrigido. Disponível na versão 8.4.5.1 ou superior
