### ISSUE TITLE
Erro ao carregar o dicionário de uma tabela (ALT + F1) no Oracle

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#3]
Não é possível visualizar o dicionário da tabela na ultima versão do Informativus, em bases Oracle.

![image](https://user-images.githubusercontent.com/22624613/103228306-453e9b00-490f-11eb-8489-0650177c7d31.png)

**Comment by wilsade** [comment]
Resolvido a partir da versão: 8.3.1.4
