### ISSUE TITLE
Perda de conexão com Oracle

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#4]
Ao deixar o informativus aberto com mais de 2h de inatividade com uma conexão Oracle, ocorre a perda de conexão com o Oracle ao executar uma nova consulta, e ela não é reestabelecida.

**1) Erro ao executar consultas: Quando é em base Oracle ao executar novamente a consulta a conexão não é reestabelecida, assim como é feito quando utilizado SQL Server.**
![image](https://user-images.githubusercontent.com/22624613/103374530-9046e280-4ab6-11eb-9375-28aac74011dd.png)

**2) Erro ao excluir a conexão Oracle na lista de conexões.**
![image](https://user-images.githubusercontent.com/22624613/103374496-82915d00-4ab6-11eb-9e6c-d51d94327860.png)

**3) Erro ao pressionar "Control + Espaço" para auto-completar algum campo ou tabela da consulta.**
![image](https://user-images.githubusercontent.com/22624613/103374480-760d0480-4ab6-11eb-951a-cd62c56b4703.png)

**4) Erro ao consultar uma tabela:**
![image](https://user-images.githubusercontent.com/22624613/103374810-401c5000-4ab7-11eb-95f2-0b03ad357ae6.png)

**Comment by wilsade** [comment]
Identificamos que esta "perda" de conexão é um bug interno:
https://download.oracle.com/otn_hosted_doc/designer/des9i_9029/deshlp72/messages/ora_messages.htm

`ORA-01041, 00000, "internal error. hostdef extension doesn't exist"`
`Cause: Pointer to hstdef extension in hstdef is null.`
`Action: Report as a bug`

Todas as mensagens de erro apresentadas são decorrentes deste BUG.
Vamos fazer um tratamento para que seja possível fechar a conexão pelo Informativus.

A correção estará disponível na próxima atualização do Informativus (versão 8.3.1.5 ou superior)
