### ISSUE TITLE
Ajustes Inicialização do Informativus

### ISSUE THREAD

**Issue by alexandrersilva** [wilsade/Informativus#5]
Ocorre erro na inicialização do aplicativo.
1-Com o arquivo de configuração da versão anterior:
System.ArgumentException: A coluna 'ExibirTelaConexao' não pertence à tabela Parametros.
   em System.Data.DataRow.GetDataColumn(String columnName)
   em System.Data.DataRow.get_Item(String columnName)
   em Informativus.Forms.Classes.ParametrosItem.MigrarDataTableParaXML(DataSet oldDataSet)
   em Informativus.Forms.MainForm.LerConfiguracao()
   em Informativus.Forms.MainForm.MainForm_Load(Object sender, EventArgs e)
   em System.EventHandler.Invoke(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em ComponentFactory.Krypton.Toolkit.KryptonForm.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em ComponentFactory.Krypton.Toolkit.VisualForm.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   
2-Sem o arquivo da versão anterior:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Informativus.Forms.Classes.ParametrosItem.MigrarDataTableParaXML(DataSet oldDataSet)
   em Informativus.Forms.MainForm.LerConfiguracao()
   em Informativus.Forms.MainForm.MainForm_Load(Object sender, EventArgs e)
   em System.EventHandler.Invoke(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em ComponentFactory.Krypton.Toolkit.KryptonForm.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em ComponentFactory.Krypton.Toolkit.VisualForm.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by wilsade** [comment]
Ajuste feito.
