### ISSUE TITLE
Dock lateral de Lista de tabelas

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#6]
O Dock lateral de Lista de tabelas: A animação executada na abertura e quando é fechada, está extremamente lenta. Poderia ser agilizada para tornar natural, ou talvez retirada a animação.

**Comment by wilsade** [comment]
O Dock é gerenciado pelo próprio componente.
Foi analisado o código fonte do Informativus e não encontramos pontos de otimização.
Optamos por alterar o componente por um **painel retrátil**.

Disponível na versão 8.4.1.5.
