### ISSUE TITLE
Auto-complete do InteliSense

### ISSUE THREAD

**Issue by tkoguta** [wilsade/Informativus#7]
Verificar a possibilidade de um novo parâmetro para considerar ter outro comportamento do intelisense, de substituir toda a palavra do cursor quando selecionado um item na listagem do Intelisense. Ao invés de simplesmente injetar o conteúdo do item selecionado onde está o cursor.

**Comment by wilsade** [comment]
Vamos gerar uma DLL protótipo para teste de aceitação.

**Comment by wilsade** [comment]
Implementado
