### ISSUE TITLE
Erro ao conectar em Base Oracle

### ISSUE THREAD

**Issue by RaCastroBR** [wilsade/Informativus#9]
Erro abaixo sendo acionado ao tentar conectar na base "BDFISCAL/I3SSERVICOS". Em outra base Oracle consegui conectar normalmente.
Versão do Informativus: 8.4.1.6

System.ArgumentException: O item já foi adicionado. Chave contida no dicionário: 'RCFUNC10'; chave sendo adicionada: 'rcfunc10'
   em WSP.Lib.WinForms.WSPProcessForm.RunInThread(String titulo, String rotuloPequeno, String descricao, Object context, DataEventVoidHandler evento, TipoExecucao tipoExecucao, EventHandler onCancelar)
   em WSP.Lib.WinForms.WSPProcessForm.RunInThread(String titulo, String descricao, Object context, DataEventVoidHandler evento, TipoExecucao tipoExecucao, EventHandler onCancelar)
   em Informativus.Forms.UserControls.ucListaTabelas.CarregarTabelasDoBancoPreencherTreeView(Object sender)
   em Informativus.Forms.UserControls.ucListaTabelas.Inicializar()
   em Informativus.Forms.Classes.ControleInformativusObj.SetDataWorkFlow()
   em Informativus.Forms.Classes.ControleInformativusObj.set_Data(DBConnect value)
   em Informativus.Forms.MainForm.ConfigurarControleInformativus()
   em Informativus.Forms.MainForm.RunConexaoBemSucedida(Object sender, DataEventArgs e)
   em WSP.Lib.WinForms.WSPProcessForm.Run(String titulo, String descricao, Object context, DataEventVoidHandler evento)
   em Informativus.Forms.MainForm.MenuItemConectar_Click(Object sender, EventArgs e)
   em ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton.OnClick(EventArgs e)
   em ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton.PerformClick()
   em ComponentFactory.Krypton.Ribbon.ViewDrawRibbonQATButton.OnClick(Object sender, MouseEventArgs e)
   em ComponentFactory.Krypton.Ribbon.LeftUpButtonController.OnClick(MouseEventArgs e)
   em ComponentFactory.Krypton.Ribbon.LeftUpButtonController.MouseUp(Control c, Point pt, MouseButtons button)
   em ComponentFactory.Krypton.Toolkit.ToolTipController.MouseUp(Control c, Point pt, MouseButtons button)
   em ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button)
   em ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button)
   em ComponentFactory.Krypton.Toolkit.ViewManager.MouseUp(MouseEventArgs e, Point rawPt)
   em ComponentFactory.Krypton.Toolkit.VisualForm.OnWM_LBUTTONUP(Message& m)
   em ComponentFactory.Krypton.Toolkit.VisualForm.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by wilsade** [comment]
A base de dados possui o mesmo objeto com mesmo nome: CAIXA ALTA  e caixa baixa.
Vou ajustar a leitura prevendo este caso.

**Comment by wilsade** [comment]
Ajuste realizado.
Disponível na versão 8.4.1.7.
